name: hw1-prototype
services:
  nginx:
    image: bitnami/nginx:1.27.0
    #command: [nginx, '-T']
    volumes:
      - ./services/nginx/app.conf:/opt/bitnami/nginx/conf/server_blocks/app.conf
      - ./public:/app
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - front
    mem_reservation: 128M
    mem_limit: 512M

  php-fpm:
    build:
      context: ./services/php-fpm
      dockerfile: php-fpm.Dockerfile
    environment:
      - PHP_FPM_LISTEN_ADDRESS=9000
      - PHP_DATE_TIMEZONE=UTC
      - PHP_ENABLE_OPCACHE=true
    volumes:
      - ./:/app
      - ./services/php-fpm/app-php.ini:/opt/bitnami/php/etc/conf.d/app.ini
    networks:
      - front
      - back
      - db-citus

  messenger-worker:
    build:
      context: ./services/php-fpm
      dockerfile: php-fpm.Dockerfile
    working_dir:
      /app
    entrypoint:
      - bin/console
      - messenger:consume
      - async
      - -vv
    environment:
      - PHP_DATE_TIMEZONE=UTC
      - PHP_ENABLE_OPCACHE=true
    volumes:
      - ./:/app
      - ./services/php-fpm/cli.ini:/opt/bitnami/php/etc/conf.d/php.ini
    networks:
      - front
      - back
    depends_on:
      redis-queue:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  db:
    image: bitnami/postgresql:16.3.0
    secrets:
      - postgresql-password
      - postgresql-replication-password
    environment:
      - POSTGRESQL_PASSWORD_FILE=/run/secrets/postgresql-password
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD_FILE=/run/secrets/postgresql-replication-password
      - POSTGRESQL_SYNCHRONOUS_REPLICAS_MODE=FIRST
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
    volumes:
      - db-data:/bitnami/postgresql
    networks:
      - back
      - db
    ports:
      - "25432:5432"
    cpus: 2
    mem_reservation: 512M
    mem_limit: 2G

  db-slave1:
    depends_on:
      - db
    image: bitnami/postgresql:16.3.0
    secrets:
      - postgresql-password
      - postgresql-replication-password
    environment:
      - POSTGRESQL_PASSWORD_FILE=/run/secrets/postgresql-password
      - POSTGRESQL_MASTER_HOST=db
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD_FILE=/run/secrets/postgresql-replication-password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
    volumes:
      - db-data-slave1:/bitnami/postgresql
    networks:
      - back
      - db
    ports:
      - '25433:5432'
    cpus: 2
    mem_reservation: 512M
    mem_limit: 2G

  db-slave2:
    depends_on:
      - db
    image: bitnami/postgresql:16.3.0
    secrets:
      - postgresql-password
      - postgresql-replication-password
    environment:
      - POSTGRESQL_PASSWORD_FILE=/run/secrets/postgresql-password
      - POSTGRESQL_MASTER_HOST=db
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD_FILE=/run/secrets/postgresql-replication-password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
    volumes:
      - db-data-slave2:/bitnami/postgresql
    networks:
      - back
      - db
    ports:
      - '25434:5432'
    cpus: 2
    mem_reservation: 512M
    mem_limit: 2G

  redis-cache:
    image: bitnami/redis:6.2
    environment:
      - REDIS_AOF_ENABLED=no
      - REDIS_PASSWORD_FILE=/run/secrets/redis-cache-password
    secrets:
      - redis-cache-password
    networks:
      - back
    ports:
      - '26379:6379'
    cpus: 1
    mem_reservation: 128M
    mem_limit: 128M

  redis-queue:
    image: bitnami/redis:6.2
    environment:
      - REDIS_AOF_ENABLED=no
      - REDIS_PASSWORD_FILE=/run/secrets/redis-queue-password
    secrets:
      - redis-queue-password
    networks:
      - back
    ports:
      - '26380:6379'
    cpus: 1
    mem_reservation: 128M
    mem_limit: 128M
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s

  citus-master:
    container_name: citus_master
    image: "citusdata/citus:12.1.3"
    ports:
      - "26432:5432"
    labels:
      - "com.citusdata.role=Master"
    environment: &CITUS_AUTH
      CITUS_HOST: citus-master
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-citus-password
      POSTGRES_HOST_AUTH_METHOD: "${POSTGRES_HOST_AUTH_METHOD:-trust}"
    secrets:
      - postgres-citus-password
    volumes:
      - citus-master:/var/lib/postgresql/data
    networks:
      - db-citus

  citus-worker-1:
    container_name: citus_worker_1
    image: "citusdata/citus:12.1.3"
    labels:
      - "com.citusdata.role=Worker"
    depends_on:
      - citus-manager
    environment: *CITUS_AUTH
    command: "/wait-for-manager.sh"
    secrets:
      - postgres-citus-password
    volumes:
      - healthcheck-volume:/healthcheck
      - citus-worker-1:/var/lib/postgresql/data
    networks:
      - db-citus

  citus-manager:
    container_name: citus_manager
    build:
      context: ./services/postgresql
      dockerfile: citus-manager.Dockerfile
    entrypoint: ["/bin/sh", "-c", "/manager-entrypoint.sh"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - healthcheck-volume:/healthcheck
    depends_on:
      - citus-master
    environment: *CITUS_AUTH
    secrets:
      - postgres-citus-password
    networks:
      - db-citus

  rabbitmq:
    image: bitnami/rabbitmq:4.0
    deploy:
      resources:
        limits:
          memory: 128M
    environment:
      RABBITMQ_USERNAME: rabbit
      RABBITMQ_PASSWORD_FILE: /run/secrets/rabbitmq-password
      RABBITMQ_MANAGEMENT_ALLOW_WEB_ACCESS: true
    volumes:
      - ./services/rabbitmq/enabled-plugins:/opt/bitnami/rabbitmq/etc/rabbitmq/enabled_plugins
    secrets:
      - rabbitmq-password
    networks:
      - back
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s

  traefik:
    image: traefik:3.2
    volumes:
      - ./services/traefik/traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik
    ports:
      - "9002:9002"

  tarantool:
    build:
      dockerfile: ./services/tarantool/Dockerfile
    environment:
     TT_APP_NAME: default
     TT_APP_DIR: /opt/tarantool/apps
     TT_INSTANCE_NAME: instance-01
    networks:
      - back
    volumes:
      - tarantool-data:/var/lib/tarantool
      - tarantool-app-data:/srv/tarantool
    healthcheck:
      test: [ "CMD", "status" ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  db-data: ~
  db-data-slave1: ~
  db-data-slave2: ~
  healthcheck-volume: ~
  citus-master: ~
  citus-worker-1: ~
  tarantool-data: ~
  tarantool-app-data: ~

networks:
  front: ~
  back: ~
  db: ~
  db-citus: ~
  traefik: ~

secrets:
  postgresql-password:
    file: ./services/postgresql/password.txt
  postgresql-replication-password:
    file: ./services/postgresql/replication-password.txt
  postgres-citus-password:
    file: ./services/postgresql/citus-password.txt
  redis-cache-password:
    file: ./services/redis/cache-password.txt
  redis-queue-password:
    file: ./services/redis/queue-password.txt
  rabbitmq-password:
    file: ./services/rabbitmq/password.txt
