name: hw1-prototype
services:
  nginx:
    image: bitnami/nginx:1.27.0
    #command: [nginx, '-T']
    volumes:
      - ./services/nginx/app.conf:/opt/bitnami/nginx/conf/server_blocks/app.conf
      - ./public:/app
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - front
    mem_reservation: 128M
    mem_limit: 512M

  php-fpm:
    build:
      context: ./services/php-fpm
      dockerfile: php-fpm.Dockerfile
    environment:
      - PHP_FPM_LISTEN_ADDRESS=9000
      - PHP_DATE_TIMEZONE=UTC
      - PHP_ENABLE_OPCACHE=true
      - PHP_MEMORY_LIMIT=256M
    volumes:
      #- ./services/php-fpm/app.conf:/opt/bitnami/php/etc/php-fpm.conf
      - ./:/app
      - ./services/php-fpm/app-php.ini:/opt/bitnami/php/etc/conf.d/app.ini
    networks:
      - front
      - back

  db:
    image: bitnami/postgresql:16.3.0
    secrets:
      - postgresql-password
      - postgresql-replication-password
    environment:
      - POSTGRESQL_PASSWORD_FILE=/run/secrets/postgresql-password
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD_FILE=/run/secrets/postgresql-replication-password
      - POSTGRESQL_SYNCHRONOUS_REPLICAS_MODE=FIRST
      - POSTGRESQL_NUM_SYNCHRONOUS_REPLICAS=1
    volumes:
      - db-data:/bitnami/postgresql
    networks:
      - back
      - db
    ports:
      - "25432:5432"
    cpus: 2
    mem_reservation: 512M
    mem_limit: 2G

  db-slave1:
    depends_on:
      - db
    image: bitnami/postgresql:16.3.0
    secrets:
      - postgresql-password
      - postgresql-replication-password
    environment:
      - POSTGRESQL_PASSWORD_FILE=/run/secrets/postgresql-password
      - POSTGRESQL_MASTER_HOST=db
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD_FILE=/run/secrets/postgresql-replication-password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
    volumes:
      - db-data-slave1:/bitnami/postgresql
    networks:
      - back
      - db
    ports:
      - '25433:5432'
    cpus: 2
    mem_reservation: 512M
    mem_limit: 2G

  db-slave2:
    depends_on:
      - db
    image: bitnami/postgresql:16.3.0
    secrets:
      - postgresql-password
      - postgresql-replication-password
    environment:
      - POSTGRESQL_PASSWORD_FILE=/run/secrets/postgresql-password
      - POSTGRESQL_MASTER_HOST=db
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=replicator
      - POSTGRESQL_REPLICATION_PASSWORD_FILE=/run/secrets/postgresql-replication-password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
    volumes:
      - db-data-slave2:/bitnami/postgresql
    networks:
      - back
      - db
    ports:
      - '25434:5432'
    cpus: 2
    mem_reservation: 512M
    mem_limit: 2G

  redis-cache:
    image: bitnami/redis:6.2
    environment:
      - REDIS_AOF_ENABLED=no
      - REDIS_PASSWORD_FILE=/run/secrets/redis-password
    secrets:
      - redis-password
    networks:
      - back
    ports:
      - '26379:6379'
    cpus: 1
    mem_reservation: 128M
    mem_limit: 128M

volumes:
  db-data: ~
  db-data-slave1: ~
  db-data-slave2: ~

networks:
  front: ~
  back: ~
  db: ~

secrets:
  postgresql-password:
    file: ./services/postgresql/password.txt
  postgresql-replication-password:
    file: ./services/postgresql/replication-password.txt
  redis-password:
    file: ./services/redis/password.txt