parameters:
    # JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR
    controller.default_json_encode_options: 0x400040

    password_hashers:
        App\Model\User:
            algorithm: auto
            cost: 13

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    _instanceof:
        App\Repository\BaseRepository:
            tags:
                - app.mapped-repository

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/DTO'
            - '../src/Entity/'
            - '../src/EventDispatcher/Event/'
            - '../src/EventDispatcher/EventType/'
            - '../src/Messenger/Message/'
            - '../src/Model/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags:
            - 'controller.service_arguments'

    Doctrine\DBAL\Connection $dbConnection: "@doctrine.dbal.default_connection"
    Doctrine\DBAL\Connection $slaveConnection: "@doctrine.dbal.slave_connection"

    Doctrine\DBAL\Connection $dbDialogConnection: "@doctrine.dbal.dialog_connection"
    Doctrine\DBAL\Connection $slaveDialogConnection: "@doctrine.dbal.dialog_connection"

    Symfony\Component\PasswordHasher\Hasher\PasswordHasherFactoryInterface:
        class: Symfony\Component\PasswordHasher\Hasher\PasswordHasherFactory
        arguments:
            - '%password_hashers%'

    Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface:
        class: Symfony\Component\PasswordHasher\Hasher\UserPasswordHasher

    App\Utils\Model\DialogInterface:
        class: App\Utils\Model\Dialog\SQLImplementation

    App\Utils\Model\Post:
        arguments:
            $feedCache: "@cache.app.post.feed"
            $feedCacheLifetime: 60
