on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  linters:
    name: "Code linters"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pre-filter modified files
        id: changed_files
        uses: dorny/paths-filter@v3
        with:
          filters: |
            php:
              - 'src/**.php'
              - 'bin/console'
              - 'public/index.php'
            frontend_js:
              - 'assets/**.js'
            any_js:
              - '**.js'
      # PHP
      - name: PHP-CS-Fixer
        if: steps.changed_files.outputs.php == 'true'
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=.php-cs-fixer.dist.php --diff --dry-run

      # JS
      - uses: actions/setup-node@v4
        if: steps.changed_files.outputs.any_js == 'true'
        with:
          node-version: 20

      - name: npm ci
        if: steps.changed_files.outputs.frontend_js == 'true'
        run: npm ci

      - name: ESLint
        if: steps.changed_files.outputs.frontend_js == 'true'
        uses: sibiraj-s/action-eslint@v3
